FROM registry.redhat.io/rhel9/rhel-bootc:9.4

ADD usr/ /usr

USER 0
ADD . .
ADD https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo12x.pt .
RUN chown -R 1001:0 ./ && \
    dnf install -y mesa-libGL && \
    dnf clean all && \
    rm -rf /var/cache/yum && \
    chmod 644 yolo12x.pt && \
    chmod 775 uploads && \
    chmod 775 runs && \
    chmod 775 runs/detect

RUN pip install -r requirements.txt