FROM registry.redhat.io/rhel9/rhel-bootc:9.6

RUN dnf -y group install GNOME base-x Fonts \
    && dnf -y clean all 

RUN dnf -y install firefox \
    && dnf -y clean all 

RUN systemctl set-default graphical.target

ADD usr/ /usr

RUN bootc container lint